### ISSUE TITLE
using ffmpeg to publish the video 

### ISSUE THREAD

**Issue by truthwzl** [MonaSolutions/MonaServer#11]
(on windows)using ffmpeg to publish the video , but only run 1minutes, then the video can't display , and audio is running.

**Comment by thomasjammet** [comment]
hi truth,

What is your ffmpeg command? And which client do you use? It's working great for me so maybe it's a configuration problem.

Have you followed the [How to publish a movie from FFMpeg to MonaServer](https://groups.google.com/forum/#!topic/monaserver/gXX0ZLzNym8) article?

Notice that there is a different behavior in ffmpeg on Windows, it requests an application in the rtmp path (like "rtmp://localhost/application/publicationame", rather than "rtmp://localhost/publicationname").
