### ISSUE TITLE
mona.clients cause the string of client.id unreadable

### ISSUE THREAD

**Issue by studease** [MonaSolutions/MonaServer#36]
function onConnection(client)
    function client:want(name)
        local farID = '43b9296f6cce011eeb4e44cd8bf7eba21efbd59e5d9df4c7e3e959d07f5b0f4a'
        local target = mona.clients(farID)
        INFO('farID: ', farID)
    end
end

The farID comes into unreadable(just the first 32 bytes) after the call of mona.clients. If the farID is not a real client id(just a string), the target is nil, but the string is still readable. I tried to get a copy of the farID, and never use it, but it became unreadable, too.
Can you please help me to figure this out? Thank you!

**Comment by MathieuPOUX** [comment]
Thanks for your reporting bug (confirmed), I am fixing it...

Temporary use "mona.clients[farID]" rather "mona.client(farID)" (mona.clients is a usual LUA table, with operator () override, and the issue is in the code of this operator).

Now if you search to get a peer by its id use netConnection.nearID  (client id) and no netConnection.farID  (server id) =>

function onConnection(client)
    function client:want(nearID)
        local target = mona.clients[nearID]
        INFO(target, 'nearID: ', nearID)
    end
end

**Comment by studease** [comment]
Thank you for your quick reply.and selfless contribution!

**Comment by MathieuPOUX** [comment]
Welcome,

You can use mona.clients(...) too now, I have just fixed it =>
https://github.com/MonaSolutions/MonaServer/commit/24e6ddff76d9849a6b06496aff784f27e05aea45

**Comment by studease** [comment]
Right, thanks a lot!
