### ISSUE TITLE
UnitTest Error

### ISSUE THREAD

**Issue by westwind027** [MonaSolutions/MonaServer#40]
Choose the index of the test to run (or type enter to run all) : 2
sources/Application.cpp[183] !ex assertion, sources/DNSTest.cpp[32]

**Comment by thomasjammet** [comment]
Hi,

I think you have a problem of DNS or networking, are you connected to internet?

Otherwise let me know which OS do you use.

Anyway UnitTest is only here for checking that our framework (MonaBase) is working well so you can ignore this error and continue to use MonaServer without problem :)

Regards
