### ISSUE TITLE
RTMP stream leaks memory Result MonaServer crash...

### ISSUE THREAD

**Issue by nobme** [MonaSolutions/MonaServer#48]
Step to reproduce problem:
Use a Apple hardware (Iphone, Ipod) with VLC to view the stream.
Set the stream on pause ( || ).
MonaServer will leak memory until the connection is automatic closed by MonaServer.
After the connection is closed, MonaServer does not leak anymore, but never releases the already leaked memory.
Start streaming again, set on pause, and the memoryleak continues.
This can be repeated until Your hardware running MonaServer run's out of memory and crash...

This is an issue on Windows and Linux. Same issue. Please fix, because MonaServer is really great, if this is fixed.

For a default MonaServer installation you can use OBS (https://obsproject.com/) for Source With stream Set to Custom and URL to  rtmp://192.168.1.2
VLC Connected to rtmp://192.168.1.2
Change the IP 192.168.1.2 to the correct IP addresse for Your system..

**Comment by MathieuPOUX** [comment]
Hi,

Yes it's unfortunately a known issue, with a little remark: if you stop all
(before crash) the memory will be released but it can takes 10 minutes...
We are working on a version 2 of Mona, which brings enhanced features and
new performance level (among others Mona2 fix this memory issue).
So sorry but patience, Mona2 should come out in few months (before april).

Best regards,
Mathieu

2017-01-25 0:56 GMT+01:00 nobme <notifications@github.com>:

**Comment by nobme** [comment]
Hmm.  Tanks for the feedback.
Really looking forward to version 2.. :)
Patience is really not my best side... Can I contribute in any way?

BR

Bjørn

**Comment by thomasjammet** [comment]
Hi Bjørn,

I think you can try with [Mona2](https://github.com/MonaSolutions/MonaServer2) on Windows for now. This is a beta version so please excuse us for the current issues, tough your reports can be useful.

In this new repository MonaServer does not compile because we have been concentrated on the protocols so you must use MonaTiny which is a small application without lua support. lua will be added in next months.

We will update the state of Mona2 to let you know which features are ready or not.

Best Regards
Thomas
