### ISSUE TITLE
RTMP settings

### ISSUE THREAD

**Issue by davidka79** [MonaSolutions/MonaServer#75]
Hello
thank you for your server it works fine, but I am Installed it on server with 32 cores, and can't find any settings for multicores? and is there any other settings for RTMP like keep alive GOP frame cache and record? idle publisher, play notifications?

**Comment by thomasjammet** [comment]
Hi David,

I copy the [answer from the forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/monaserver/tIMiwy9tc-s) here :

> For cores settings there is few options (like "threads") in .ini file, see here =>
> http://www.monaserver.ovh/installation.html#configurations
> 
> For streaming options all have to be configured on client side, MonaServer relays just stream between peers (in real-time, without any buffering). So I invite you to see documentation of your client (if your client is RTMP NetStream documentation).

In addition take a look at our documentation, especially [the Client API](http://www.monaserver.ovh/api.html#client) which will give you some tips to work with publications and players.

I hope we will have time soon to add lua to MonaServer2 because there is a lot more useful features that we would like to share with our users (recording, http publish, asynchronous file read/write...).

Regards
